/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ironcutpro;

/**
 *
 * @author main_
 */
public class ResultadoPanel extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoPanel
     */
    public ResultadoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TotalTrozos = new javax.swing.JLabel();
        TamañoTrozos = new javax.swing.JLabel();
        ResiduoTrozos = new javax.swing.JLabel();
        CostoTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        FinalizarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel2.setText("IRON CUT PRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.orange);
        jLabel3.setText("El Total de Trosos es:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.orange);
        jLabel4.setText("El tamaño de los Trozos es:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.orange);
        jLabel5.setText("El Residuo de los cortes es");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        TotalTrozos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalTrozos.setForeground(new java.awt.Color(204, 204, 204));
        TotalTrozos.setText("jLabel6");
        getContentPane().add(TotalTrozos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        TamañoTrozos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TamañoTrozos.setForeground(new java.awt.Color(204, 204, 204));
        TamañoTrozos.setText("jLabel7");
        getContentPane().add(TamañoTrozos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));

        ResiduoTrozos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResiduoTrozos.setForeground(new java.awt.Color(204, 204, 204));
        ResiduoTrozos.setText("jLabel8");
        getContentPane().add(ResiduoTrozos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        CostoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostoTotal.setForeground(java.awt.Color.orange);
        CostoTotal.setText("El costo Total es:");
        getContentPane().add(CostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        Atras.setBackground(new java.awt.Color(102, 102, 102));
        Atras.setForeground(new java.awt.Color(153, 255, 153));
        Atras.setText("Atras");
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));

        FinalizarCompra.setBackground(new java.awt.Color(153, 255, 153));
        FinalizarCompra.setForeground(new java.awt.Color(102, 102, 102));
        FinalizarCompra.setText("Finalizar Compra");
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(FinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironcutpro/Imagenes/FondoHD.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 669, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ResultadoPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel CostoTotal;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JLabel ResiduoTrozos;
    private javax.swing.JLabel TamañoTrozos;
    private javax.swing.JLabel TotalTrozos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
