/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ironcutpro;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author main_
 */
public class ResultadoPanel extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoPanel
     */
    Registro<List<Pedido>> historial=new Registro("historial.txt");
    Registro<Pedido> reg=new Registro<>("pedidoActual.txt");
    Pedido temp;
    public ResultadoPanel() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        temp=reg.cargar();
        float manoObra=10*temp.obtenerCantidad();
        float material=1;
        if(temp.barraInicial.obtenerMaterial().equals("Madera"))
        {
            material=5;
        }
        if(temp.barraInicial.obtenerMaterial().equals("Hierro"))
        {
            material=10;
        }
        if(temp.barraInicial.obtenerMaterial().equals("Cobre"))
        {
            material=15;
        }
        if(temp.barraInicial.obtenerMaterial().equals("Acero"))
        {
            material=20;
        }
        float costoTotal=manoObra+material*temp.barraInicial.obtenerLongitud();
        temp.setCostoTotal(costoTotal);
        TotalTrozos.setText(""+temp.obtenerCantidad());
        TamañoTrozos.setText(""+temp.barraInicial.obtenerLongitud()/temp.obtenerCantidad());
        jLabel10.setText(""+costoTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TotalTrozos = new javax.swing.JLabel();
        TamañoTrozos = new javax.swing.JLabel();
        CostoTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FinalizarCompra = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Mongolian Baiti", 1, 48)); // NOI18N
        jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel2.setText("IRON CUT PRO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.orange);
        jLabel3.setText("El Total de Trosos es:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.orange);
        jLabel4.setText("El tamaño de los Trozos es:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        TotalTrozos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TotalTrozos.setForeground(new java.awt.Color(204, 204, 204));
        TotalTrozos.setText(" ");
        getContentPane().add(TotalTrozos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 90, -1));

        TamañoTrozos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TamañoTrozos.setForeground(new java.awt.Color(204, 204, 204));
        TamañoTrozos.setText(" ");
        getContentPane().add(TamañoTrozos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 150, -1));

        CostoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CostoTotal.setForeground(java.awt.Color.orange);
        CostoTotal.setText("El costo Total es:");
        getContentPane().add(CostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText(" ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 120, -1));

        FinalizarCompra.setBackground(new java.awt.Color(153, 255, 153));
        FinalizarCompra.setForeground(new java.awt.Color(102, 102, 102));
        FinalizarCompra.setText("Finalizar Compra");
        FinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(FinalizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ironcutpro/Imagenes/FondoHD.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 669, 475));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarCompraActionPerformed
        try {
            // TODO add your handling code here:
            List<Pedido> temp=new ArrayList<>();
            temp=historial.cargar();
            temp.add(this.temp);
            historial.guardar(temp);
            reg.guardar(this.temp);
            this.setVisible(false);
            CambioPanel c=new CambioPanel();
            c.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ResultadoPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ResultadoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_FinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new ResultadoPanel().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(ResultadoPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ResultadoPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CostoTotal;
    private javax.swing.JButton FinalizarCompra;
    private javax.swing.JLabel TamañoTrozos;
    private javax.swing.JLabel TotalTrozos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
